build: glfsheal should link against $(UUID_LIBS)
Without this, building fails on Debian Jessie:

    /usr/bin/ld: glfs-heal.o: undefined reference to symbol 'uuid_clear@@UUID_1.0'
    /lib/x86_64-linux-gnu/libuuid.so.1: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    Makefile:503: recipe for target 'glfsheal' failed

While at it, clean some of the unused defines too.

BUG: 1206587
Change-Id: I2e513b2a806e6241542e60007d720cca16dabb06
Signed-off-by: Niels de Vos <ndevos@redhat.com>
Reviewed-on: http://review.gluster.org/10453
Tested-by: Gluster Build System <jenkins@build.gluster.com>
Reviewed-by: Kaleb KEITHLEY <kkeithle@redhat.com>