build: remove unneeded include <sys/user.h> for FreeBSD
The include <sys/user.h> causes a conflicting definition of an RPC
'struct pmap':

    --- fuse-helpers.lo ---
    In file included from /usr/include/rpc/rpc.h:73:0,
                     from ../../../../libglusterfs/src/glusterfs-fops.h:35,
                     from /usr/home/jenkins/root/workspace/freebsd-smoke/libglusterfs/src/glusterfs.h:32,
                     from /usr/home/jenkins/root/workspace/freebsd-smoke/xlators/mount/fuse/src/fuse-bridge.h:22,
                     from /usr/home/jenkins/root/workspace/freebsd-smoke/xlators/mount/fuse/src/fuse-helpers.c:26:
    /usr/include/rpc/pmap_prot.h:89:8: error: redefinition of 'struct pmap'
     struct pmap {
            ^
    In file included from /usr/include/vm/pmap.h:90:0,
                     from /usr/include/sys/user.h:52,
                     from /usr/home/jenkins/root/workspace/freebsd-smoke/xlators/mount/fuse/src/fuse-helpers.c:19:
    /usr/include/machine/pmap.h:299:8: note: originally defined here
     struct pmap {
            ^

It seems that building on FreeBSD still functions without any additional
warnings or errors, even when the include is removed.

Change-id I98fc8cf7e4b631082c7b203b5a0a77111bec1fb9 identified this
issue, and this build-fix is needed for applying I98fc8cf7.

BUG: 1198849
Change-Id: Ib8241b7dc47eb2c3593d2f8ea1d196178e63d02d
Signed-off-by: Niels de Vos <ndevos@redhat.com>
Reviewed-on: http://review.gluster.org/14093
NetBSD-regression: NetBSD Build System <jenkins@build.gluster.org>
Smoke: Gluster Build System <jenkins@build.gluster.com>
CentOS-regression: Gluster Build System <jenkins@build.gluster.com>
Reviewed-by: Jeff Darcy <jdarcy@redhat.com>