fix fedora smoke warning for rdma
Warning:
rpc/rpc-transport/rdma/src/rdma.c:2008:16: error: taking address of packed member of ‘union <anonymous>’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
chunkptr = &hdr->rm_body.rm_chunks[0];

Fix:
Use Wno-address-of-packed-member for now since rdma is removed from devel
branch.

Change-Id: I8586c2d0d21d7c8c2c3274d3391e6600c089ac8f
Signed-off-by: Ravishankar N <ravishankar@redhat.com>