snapshot: svc_stat collides with define from /usr/include/rpc/svc.h
Compiling fails with this error:

    snapview-client.c:559:24: error: macro "svc_stat" passed 4 arguments, but takes just 1
               dict_t *xdata)
                            ^
    snapview-client.c:560:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
     {
     ^
    snapview-client.c:2412:26: error: ‘svc_stat’ undeclared here (not in a function)
             .stat          = svc_stat,
                              ^

svc_* is the common prefix for (SUN)RPC functions provided by system
headers. svc_stat() seems to be an existing function name. This happens
because change-id I98fc8cf7e4b631082c7b203b5a0a77111bec1fb9 causes
<rpc/rpc.h> included through "glusterfs.h". Prepending gf_ for all svc_*
functions works around the symbol collision.

Change-Id: Idc86b719c48675a5154c54d844c1899d14d46e2a
BUG: 1328502
Signed-off-by: Niels de Vos <ndevos@redhat.com>
Reviewed-on: http://review.gluster.org/14035
Smoke: Gluster Build System <jenkins@build.gluster.com>
Reviewed-by: Rajesh Joseph <rjoseph@redhat.com>
Reviewed-by: Kaleb KEITHLEY <kkeithle@redhat.com>
CentOS-regression: Gluster Build System <jenkins@build.gluster.com>
NetBSD-regression: NetBSD Build System <jenkins@build.gluster.org>