features/libgfchangelog: Fix coverity issues
Error: DEADCODE:
xlators/features/changelog/lib/src/gf-changelog-journal-handler.c:524:
dead_error_begin: Execution cannot reach this statement: "default:".

Error: DEADCODE:
xlators/features/changelog/lib/src/gf-history-changelog.c:984:
dead_error_line: Execution cannot reach the expression "to" inside
this statement: "if (!from || !to)
  ret = -1;".

Error: REVERSE_INULL:
xlators/features/changelog/lib/src/gf-changelog-journal-handler.c:678:
check_after_deref: Null-checking "entry" suggests that it may be null,
but it has already been dereferenced on all paths leading to the
check.

Error: STACK_USE:
xlators/features/changelog/lib/src/gf-changelog-journal-handler.c:275:
stack_use_local_overflow: Local variable "ascii" uses 12288 bytes of
stack space, which exceeds the maximum single use of 10000 bytes.

Error: STACK_USE:
xlators/features/changelog/lib/src/gf-changelog-journal-handler.c:167:
stack_use_local_overflow: Local variable "ascii" uses 12288 bytes of
stack space, which exceeds the maximum single use of 10000 bytes.

Error: STRING_NULL:
xlators/features/changelog/lib/src/gf-changelog-journal-handler.c:589:9:
string_null_sink_parm_call: Passing parameter "from_path" to "open"
which expects a null-terminated string.

Error: UNUSED_VALUE:
xlators/features/changelog/lib/src/gf-history-changelog.c:628:
assigned_value: Assigning value "-1" to "ret" here, but that stored
value is overwritten before it can be used.

Error: STRING_NULL:
xlators/features/changelog/lib/src/gf-history-changelog.c:518:
string_null_argument: Function "sys_pread" does not terminate string
"*ccd->changelog".

BUG: 789278
Change-Id: I1414ec6d4a118ce0c14df4dbe50995c85fe3ecf7
Signed-off-by: Aravinda VK <avishwan@redhat.com>