pump: Fixed undefined reference to fill_loc_info fn.
Changed function to pump_fill_loc_info since its use is relevant
only in pump's context.

Change-Id: I5be1a908f88328f732dacfd7eac18f0c62f49eb8
BUG: 796066
Signed-off-by: Krishnan Parthasarathi <kp@gluster.com>
Reviewed-on: http://review.gluster.com/2796
Tested-by: Gluster Build System <jenkins@build.gluster.com>
Reviewed-by: Pranith Kumar Karampuri <pranithk@gluster.com>
Reviewed-by: Vijay Bellur <vijay@gluster.com>