libglusterfs: Fix openSUSE build error
GlusterFS failed during make on openSUSE Tumbleweed with the following
error:

Making all in fdl
Making all in src
  CC       logdump.o
  CC       recon.o
  CC       fdl.lo
  CC       librecon.o
  CC       libfdl.o
  CCLD     gf_logdump
  CCLD     gf_recon
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../lib64/libfl.so: undefined reference to `yylex'
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:618: gf_logdump] Error 1
make[5]: *** Waiting for unfinished jobs....
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../lib64/libfl.so: undefined reference to `yylex'
collect2: error: ld returned 1 exit status

Reading through autoconf manual[1](see AC_PROG_LEX) reveals that LEXLIB
is automatically set to appropriate value for the system. The reference
to LEXLIB in automake file caused the above mentioned error on openSUSE.
In particular, we do not bother about LEXLIB hereafter.

[1] https://www.gnu.org/software/autoconf/manual/autoconf.html#Particular-Programs

Change-Id: I9bfce80c9654b2e3bfb393b08c25e8ad3d79e449
BUG: 1493133
Signed-off-by: Anoop C S <anoopcs@redhat.com>