cli: fix build error with --disable-xml-output
./configure --disable-xml-output --disable-georeplication
make

Making all in src
  CC       cli.o
In file included from cli.c:42:0:
cli.h:440:24: error: unknown type name ‘xmlTextWriterPtr’
 cli_xml_output_common (xmlTextWriterPtr writer, int op_ret, int op_errno,
                        ^
cli.h:443:26: error: unknown type name ‘xmlTextWriterPtr’
 cli_xml_snapshot_delete (xmlTextWriterPtr writer, xmlDocPtr doc, dict_t *dict,
                          ^
cli.h:443:51: error: unknown type name ‘xmlDocPtr’
 cli_xml_snapshot_delete (xmlTextWriterPtr writer, xmlDocPtr doc, dict_t *dict,
                                                   ^
make[1]: *** [cli.o] Error 1
make: *** [all-recursive] Error 1

Change-Id: I36c2dfc11f89d774b62dfe6f50b156826bed5b66
Signed-off-by: Kinglong Mee <mijinlong@open-fs.com>
Reviewed-on: https://review.gluster.org/17136
Smoke: Gluster Build System <jenkins@build.gluster.org>
Reviewed-by: Atin Mukherjee <amukherj@redhat.com>
Reviewed-by: Prashanth Pai <ppai@redhat.com>
Tested-by: Prashanth Pai <ppai@redhat.com>
NetBSD-regression: NetBSD Build System <jenkins@build.gluster.org>
CentOS-regression: Gluster Build System <jenkins@build.gluster.org>